# Generated by Django 4.2.28 on 2026-02-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "платёж", "verbose_name_plural": "платежи"},
        ),
    ]
