# Generated by Django 4.2.28 on 2026-03-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_rename_payment_payment_amount_payment_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(
                help_text="Введите сумму платежа", verbose_name="Сумма платежа"
            ),
        ),
    ]
