# Generated by Django 4.2.28 on 2026-03-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=600,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
    ]
