# Generated by Django 4.2.28 on 2026-03-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_payment_link_alter_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Введите сумму платежа",
                null=True,
                verbose_name="Сумма платежа",
            ),
        ),
    ]
