# Generated by Django 4.2.28 on 2026-03-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_payment_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                blank=True,
                help_text="Статус платежа в Stripe",
                max_length=50,
                null=True,
                verbose_name="Статус платежа",
            ),
        ),
    ]
