# Generated by Django 4.2.28 on 2026-03-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Стоимость курса",
                max_digits=10,
                verbose_name="Цена",
            ),
        ),
    ]
