# Generated by Django 4.2.28 on 2026-03-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Стоимость урока",
                max_digits=10,
                verbose_name="Цена",
            ),
        ),
    ]
