# Generated by Django 4.2.28 on 2026-03-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_lesson_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(
                default=0, help_text="Стоимость урока", verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="price",
            field=models.PositiveIntegerField(
                default=0, help_text="Стоимость урока", verbose_name="Цена"
            ),
        ),
    ]
